### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by b2whats** [babel-plugins/babel-plugin-dead-code-elimination#1]
└─ $ ▶ babel --plugins dead-code-elimination test.js
```javascript
TypeError: undefined is not a function
at exports.default (/home/w/PhpstormProjects/my-starter-kit/node_modules/babel-plugin-dead-code-elimination/lib/index.js:28:10)
at Function.memoisePluginContainer (/usr/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:46:23)
at PluginManager.add (/usr/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:131:30)
at File.buildTransformers (/usr/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:290:21)
at new File (/usr/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:148:10)
at TransformerPipeline.transform (/usr/lib/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:96:16)
at Object.exports.transform (/usr/lib/node_modules/babel/bin/babel/util.js:33:22)
at Object.exports.compile (/usr/lib/node_modules/babel/bin/babel/util.js:41:18)
at /usr/lib/node_modules/babel/bin/babel/file.js:120:23
at arrayEach (/usr/lib/node_modules/babel/node_modules/lodash/index.js:1314:13)
```

**Comment by sebmck** [comment]
These plugins wont work until the next version of Babel.
